dist: focal

language: csharp
mono: none
dotnet: 5.0

before_script:
  - dpkg -L libcharls2

script:
  - dotnet restore
  - dotnet build
  - dotnet test

addons:
  apt:
    packages:
      - libcharls2
